#PANDAS ile Veri Üzerinde İşlemler Yapmak

##https://pandas.pydata.org/

Python Data Analysis Library
pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

1 - Önceden tanımlanmış bir ülke listesi oluşturalım

In [0]:
# Pre-defined lists
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

# Create dictionary my_dict with three key:value pairs: my_dict
my_dict = {'country':names, 'drives_right':dr, 'cars_per_cap':cpc}

In [0]:
# pandas kütüphanesini import komutu ile yüklüyoruz.
import pandas as pd
# Build a DataFrame cars from my_dict: cars
cars = pd.DataFrame(my_dict)

# Print cars
print(cars)

NameError: ignored

In [0]:
# Definition of row_labels
row_labels = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# Specify row labels of cars
cars.index = row_labels

# Print cars again
print(cars)

           country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JAP          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [0]:
# Import the cars.csv data: cars
#cars = pd.read_csv("~/Downloads/cars.csv")
cars = pd.read_csv("https://raw.githubusercontent.com/TheJackalTR/pySession-1/master/cars.csv")

# Print out cars
print(cars)

  Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JPN           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

In [0]:
# Fix import by including index_col
#cars = pd.read_csv('~/Downloads/cars.csv', index_col = 0)
cars = pd.read_csv('https://raw.githubusercontent.com/TheJackalTR/pySession-1/master/cars.csv', index_col = 0)

# Print out cars
print(cars)

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JPN           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [0]:
# Print out country column as Pandas Series
print(cars["country"])

US     United States
AUS        Australia
JPN            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: country, dtype: object

In [0]:
# Print out country column as Pandas DataFrame
print(cars[["country"]])

           country
US   United States
AUS      Australia
JPN          Japan
IN           India
RU          Russia
MOR        Morocco
EG           Egypt

In [0]:
# Print out DataFrame with country and drives_right columns
print(cars[["country","drives_right"]])

           country  drives_right
US   United States          True
AUS      Australia         False
JPN          Japan         False
IN           India         False
RU          Russia          True
MOR        Morocco          True
EG           Egypt          True

In [0]:
# Print out first 3 observations
print(cars[0:3])

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JPN           588          Japan         False

In [0]:
# Print out fourth, fifth and sixth observation
print(cars[3:6])

     cars_per_cap  country  drives_right
IN             18    India         False
RU            200   Russia          True
MOR            70  Morocco          True

In [0]:
# Print out observation for Japan
print(cars.loc["JPN"])
# print(cars.iloc[2])

cars_per_cap      588
country         Japan
drives_right    False
Name: JPN, dtype: object

In [0]:
print(cars.loc[["JPN"]])
# print(cars.iloc[[2]])

     cars_per_cap country  drives_right
JPN           588   Japan         False

In [0]:
# Print out drives_right value of Morocco
print(cars.loc["MOR","drives_right"])

True

In [0]:
# Print sub-DataFrame
print(cars.loc[["RU","MOR"],["country","drives_right"]])

     country  drives_right
RU    Russia          True
MOR  Morocco          True

In [0]:
# Print out drives_right column as Series
print(cars.loc[:,"drives_right"])

US      True
AUS    False
JPN    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool

In [0]:
# Print out drives_right column as DataFrame
print(cars.loc[:,["drives_right"]])

     drives_right
US           True
AUS         False
JPN         False
IN          False
RU           True
MOR          True
EG           True

In [0]:
# Print out cars_per_cap and drives_right as DataFrame
print(cars.loc[:, ['cars_per_cap', 'drives_right']])

     cars_per_cap  drives_right
US            809          True
AUS           731         False
JPN           588         False
IN             18         False
RU            200          True
MOR            70          True
EG             45          True